;;;; named.lisp

(in-package :coca.appkit)

(defclass named-mixin ()
  ((name
    :initarg  :name
    :type     string
    :reader   name
    :documentation
    "Name of `named-mixin'")
   (%name-gen
    :initform   0
    :allocation :class
    :documentation
    "Counter to generate "))
  (:documentation
   "Mixin class to add autogenerated name. "))

(defmethod initialize-instance :after ((named named-mixin) &key)
  (unless (slot-boundp named 'name)
    (setf (slot-value named 'name)
          (format nil "~A~D"
                  (class-name (class-of named))
                  (incf (slot-value named '%name-gen))))))

;;;; named.lisp ends here
