#+title: Coca.ObjC
#+subtitle: Minimal CFFI ObjC bindings
#+author: 凉凉
* Usage
:PROPERTIES:
:header-args:lisp: :package coca.objc :results verbatim
:END:

** Invoke
Invoke ObjC method with macro [[doc:invoke][=invoke=]]:

#+begin_src lisp
(description (invoke "NSString" "stringWithUTF8String:" :string "Hello World" :object))
#+end_src

#+RESULTS:
: Hello World

Or use the shortcut function:

#+begin_src lisp :results silent
(cffi:foreign-funcall "NSLog" :pointer (string-to-ns-string "Hello World"))
#+end_src

which should print out like:

#+begin_example
2026-03-10 20:42:23.575 sbcl[21728:11113876] Hello World
#+end_example

Note that ObjC errors are not handled by lisp, which just kills the lisp
image. Be aware to call ObjC methods correctly or check before calling.

** Typing
The macro [[doc:invoke][=invoke=]] is just a thin warpper on =cffi:foreign-funcall=.

*** ObjC typing via alias
For example:

#+begin_src lisp :eval no
(invoke "NSString" "stringWithUTF8String:" :string "Hello World" :object)
#+end_src

would be expanded into

#+begin_src lisp :eval no
(foreign-funcall
 "objc_msgSend"
 :pointer (objc-class-ptr #<NSString 1F9E6A100>)
 :pointer (sel-ptr #<sel stringWithUTF8String: 20890E8C0>)
 :string "Hello World"
 :pointer)
#+end_src

with typing alias:

#+begin_src lisp :eval no
(define-objc-typing :object
  :alias :pointer)
#+end_src

*** Complex ObjC typing transforming rules
For complex transforming rules:

#+begin_src lisp :eval no
(invoke ns-object "description" :ns-string)
#+end_src

would be expanded into

#+begin_src lisp :eval no
(ns-string-to-string
 (foreign-funcall
  "objc_msgSend"
  :pointer (mcclim-coca.objc::objc-pointer ns-object)
  :pointer (mcclim-coca.objc::sel-ptr #<sel description 208A1BFE0>)
  :pointer))
#+end_src

with result and input args rules:

#+begin_src lisp :eval no
(define-objc-typing :ns-string
  :result (:pointer ns-string-to-string)
  :arg    ((str `(:pointer (string-to-ns-string ,str)))))
#+end_src

the =:arg= parameter can be a list of elements =(PATTERN EXPANSION-RULE)=
+ =PATTERN=: the pattern use [[https://github.com/m2ym/optima][=optima:match=]] to match patterns
+ =EXPANSION-RULE=: an expression evaluated

  the return value(s) can be arg expansion and invoke rewrite
  + arg expansion: should be like a list of =(:CFFI-TYPE EXPR ...)=
  + invoke rewrite: wrap =invoke= like =`(,@rewrite (invoke ...))=

*** Built-in ObjC typing
Coca.ObjC provides some built-in ObjC typing:

| ObjC typing  | CFFI equivent                      | ~invoke~ as return value |
|--------------+------------------------------------+--------------------------|
| ~:class~     | ~:pointer~                         | ~coerce-to-objc-class~   |
| ~:sel~       | ~:pointer~                         | ~coerce-to-selector~     |
| ~:object~    | ~:pointer~                         |                          |
| ~:ns-array~  | ~:pointer~ (not implemented yet)   | ~ns-array-to-list~       |
| ~:ns-string~ | ~:pointer~ (~string-to-ns-string~) | ~ns-string-to-string~    |
| ~:block~     | ~:pointer~ (ObjC's block)          | (not implemented)        |

Can use =define-objc-typing= macro to define a new ObjC typing.

** Block
Some ObjC functions expect blocks as arguments, which can be invoked
like:

#+begin_src lisp :eval no
(invoke obj "methodWithBlock:" :block (BLOCK-TYPE (LAMBDA-LIST) &body ...))
#+end_src

Use =define-objc-block= to define your own =block-type=.

** Image Dump
Since Coca.ObjC is built on ObjC's runtime, every time you terminate
the ObjC runtime, you have to re-initialize it.

Use =define-objc-global-variable= to define a global variable access
function like:

#+begin_src lisp :eval no
(define-objc-global-variable my-ns-string
  (string-to-ns-string "My NSString")
  "Just to demo it")
#+end_src

Use the function =my-ns-string= to access the global variable
=*my-ns-string*= to ensure it would be correctly setted up.

** macOS version and test
Load =coca/objc/osx-version= subsystem to get the ability to get/test
macOS version.

Use [[doc:osx-version][=(osx-version)=]] to get current macintosh major, minor and patch version.
More commonly, use [[doc:osx-version>=][~(osx-version>= major &optional minor patch)~]] to test
system version requirements.

* API
:PROPERTIES:
:header-args:lisp: :package coca.objc :results verbatim
:END:

+ =*objc-libraries*= *[Variable]*

  #+name: doc:*objc-libraries
  #+begin_src lisp :exports results
  (documentation '*objc-libraries* 'variable)
  #+end_src

  #+RESULTS: doc:*objc-libraries
  : A list of foreign libraries names.
  :
  : To load new ObjC libraries:
  :
  :     (define-foreign-library lib-name
  :       (:darwin (:framework \"...\")))
  :     (load-foreign-library 'lib-name)
  :     (pushnew 'lib-name *objc-libraries*)
  :

+ =(invoke CLASS-OR-OBJECT SEL [TYPE ARG]* [RETURN-TYPE]?)= *[Macro]*

  #+name: doc:invoke
  #+begin_src lisp :exports results
  (documentation (macro-function 'invoke) t)
  #+end_src

  #+RESULTS: doc:invoke
  #+begin_example
  Invokes an ObjC method that returns RESULT CFFI type.

  Syntax:

      (invoke CLASS-OR-OBJECT METHOD
              { OBJC-TYPE VAR }*
              [ (RESULT :void) ])

  Parameters:
  + CLASS-OR-OBJECT: things can be converted via `objc-pointer'
  + METHOD: a string naming the method to invoke
  + OBJC-TYPE: extended CFFI type

    Built-in ObjC typing:
    + :object   expecting to be `objc-object'
    + :class    expecting to be `objc-class'
    + :sel      expecting to be `sel'
    + :ns-uint  alias as :unsigned-long
    + :ns-int   alias as :long
    + :cg-float alias as :double

    Built-in ObjC typing in `coca/objc/block' subsystem:
    + :block    expecting (BLOCK-TYPE (lambda-list ...) ,@body)
      see `define-objc-block' for details

    Built-in ObjC typing in `coca/appkit' subsystem:
    + :ns-rect  expecting (X Y W H) inline value passing
    + :ns-point expecting (X Y) inline value passing
    + :ns-size  expecting (W H) inline value passing

    Use `define-objc-typing' to define new ObjC typing.
  + RESULT:

    Built-in ObjC typing:
    + :ns-array return `list' of `foreign-pointer'

    Use `define-objc-typing' to define new ObjC typing.

    If not provided, by default as `:void'

  #+end_example

+ =(invoke-super OBJECT SEL [TYPE ARG]* [RETURN-TYPE]?)= *[Macro]*

  #+name: doc:invoke-super
  #+begin_src lisp :exports results
  (documentation (macro-function 'invoke-super) t)
  #+end_src

  #+RESULTS: doc:invoke-super
  #+begin_example
  Invokes an ObjC method that returns RESULT CFFI type.

  Syntax:

      (invoke-super OBJECT METHOD
                    { OBJC-TYPE VAR }*
                    [ (RESULT :void) ])

  Parameters:
  + OBJECT: `objc-object'
  + METHOD: a string naming the method to invoke
  + OBJC-TYPE: extended CFFI type

    Built-in ObjC typing:
    + :object   expecting to be `objc-object'
    + :class    expecting to be `objc-class'
    + :sel      expecting to be `sel'
    + :ns-uint  alias as :unsigned-long
    + :ns-int   alias as :long
    + :cg-float alias as :double

    Built-in ObjC typing in `coca/objc/block' subsystem:
    + :block    expecting (BLOCK-TYPE (lambda-list ...) ,@body)
      see `define-objc-block' for details

    Built-in ObjC typing in `coca/appkit' subsystem:
    + :ns-rect  expecting (X Y W H) inline value passing
    + :ns-point expecting (X Y) inline value passing
    + :ns-size  expecting (W H) inline value passing

    Use `define-objc-typing' to define new ObjC typing.
  + RESULT:

    Built-in ObjC typing:
    + :ns-array return `list' of `foreign-pointer'

    Use `define-objc-typing' to define new ObjC typing.

    If not provided, by default as `:void'
  #+end_example

+ =(with-autorelease-pool &body)= *[Macro]*

  #+name: doc:with-autorelease-pool
  #+begin_src lisp :exports results
  (documentation (macro-function 'with-autorelease-pool) t)
  #+end_src

  #+RESULTS: doc:with-autorelease-pool
  : Wrap BODY within ObjC autorelease pool block.

+ =sel= *[Struct]*

+ =objc-class= *[Struct]*

+ =(coerce-to-selector sel)= *[Function]*

  #+name: doc:coerce-to-selector
  #+begin_src lisp :exports results
  (documentation #'coerce-to-selector t)
  #+end_src

  #+RESULTS: doc:coerce-to-selector
  : Return cached `sel' for ObjC SEL.

+ =(coerce-to-objc-class class)= *[Function]*

  #+name: doc:coerce-to-objc-class
  #+begin_src lisp :exports results
  (documentation #'coerce-to-objc-class t)
  #+end_src

  #+RESULTS:
  : Return cached `objc-class' for ObjC Class.

+ =(define-objc-class class superclass &rest protocols)= *[Macro]*

  #+name: doc:define-objc-class
  #+begin_src lisp :exports results
  (documentation (macro-function 'define-objc-class) t)
  #+end_src

  #+RESULTS: doc:define-objc-class
  #+begin_example
  Define ObjC Class if needed.

  This is equal to calling ObjC Code:

  @interface CLASS : SUPERCLASS < PROTOCOLS... >
  @end

  + CLASS:
    string of ObjC Class
  + SUPERCLASS:
    string of superclass of ObjC Class
  + PROTOCOLS:
    strings of ObjC Protocols
  #+end_example

+ =(define-objc-method (class sel &key encoding callback) return-type lambda-list &body)= *[Macro]*

  #+name: doc:define-objc-method
  #+begin_src lisp :exports results
  (documentation (macro-function 'define-objc-method) t)
  #+end_src

  #+RESULTS: doc:define-objc-method
  #+begin_example
  Define ObjC instance method.

  Syntax:

      (define-objc-method (CLASS SEL &key ENCODING CALLBACK)
           RETURN-TYPE
           LAMBDA-LIST
        &body
        SELF...)

  + CLASS:
    literal string of ObjC class name
  + SEL:
    literal string of ObjC SEL name
  + ENCODING:
    method encoding type string
    if not given, will use class_replaceMethod with types as NULL pointer;
    if given, should be like a string starting with @:
  + CALLBACK
    custom CFFI callback symbol name
  + RETURN-TYPE:
    cffi return type with ObjC type enhanced
    + `:object'  same as :pointer
    + `:class'   return value will be wrapped as `objc-class-ptr'
    + `:sel'     return value will be wrapped as `sel-ptr'
    + otherwise see CFFI foreign types
  + LAMBDA-LIST:
    same as `cffi:defcallback', or defined in `define-objc-typing'
  + BODY
    method body,
    within the BODY, self is bound to foreign-pointer of ObjC object
  #+end_example

+ =(define-objc-global-variable reader initial-form &optional documentation)= *[Macro]*

  #+name: doc:define-objc-global-variable
  #+begin_src lisp :exports results
  (documentation (macro-function 'define-objc-global-variable) t)
  #+end_src

  #+RESULTS: doc:define-objc-global-variable
  #+begin_example
  Define ObjC global variable accessor function of NAME.
  The global variable is initialized with INITIALIZE-FORM.

  Syntax:

      (define-objc-global-variable NAME
          INITIALIZE-FORM
        [DOCUMENTATION])

  + NAME: symbol of global reader function name
  + INITIALIZE-FORM: initialization form
  + DOCUMENTATION: optional documentation string for NAME function

  Dev Note:
  + there would also be a global variable with name like `*NAME*'
    it should not be used directly since it should be cleared
    when ObjC runtime initialized and might not properly initialized;
  + this macro acts like `defvar', so if the global variable
    is defined already (and non-nil), it's INITIALIZE-FORM should
    only run once.
  #+end_example

+ =*on-objc-initialization*= *[Variable]*

  #+name: doc:*on-objc-initialization*
  #+begin_src lisp :exports results
  (documentation '*on-objc-initialization* 'variable)
  #+end_src

  #+RESULTS: doc:*on-objc-initialization*
  : A list of ObjC initialize callbacks.
  :
  : The element should be callback function symbol
  : or function to call after `ensure-objc-initialized'.
  :
  : The function will be called with no argument.

+ =(ensure-objc-initialized)=  *[Function]*

  #+name: doc:ensure-objc-initialized
  #+begin_src lisp :exports results
  (documentation #'ensure-objc-initialized t)
  #+end_src

  #+RESULTS: doc:ensure-objc-initialized
  #+begin_example
  Restore ObjC environment after restore image.

  Dev Note:
  1. the ObjC libraries will be reloaded first

     Example: add custom ObjC library

     (define-foreign-library OBJC-LIB
       (:darwin (:framework \"ObjCLibrary\"))
     (pushnew 'OBJC-LIB *objc-libraries*)

  2. the SEL and Class pointer will be rebinded,
     and for thoese dynamic created ObjC class,
     they will be registed at this stage

     it is strongly not recommanded to directly
     store foreign-pointer of `sel' or `objc-class'

  3. the global ObjC variables defined by
     `define-objc-global-variable' will be re-initialized
     using their INITIALIZE-FORM

  4. call hooks in `*on-objc-initialization*'
  #+end_example

+ =(define-objc-typing name &key alias result arg)= *[Macro]*

  #+name: doc:define-objc-typing
  #+begin_src lisp :exports results
  (documentation (macro-function 'define-objc-typing) t)
  #+end_src

  #+RESULTS: doc:define-objc-typing
  #+begin_example
  Define ObjC typing of NAME.

  Syntax:

      (define-objc-typing NAME
        :alias  ALIAS
        :result RESULT
        :arg    ARG)

  + NAME:  (recommanded to be) a keyword for ObjC typing name
  + ALIAS:
    + CFFI typing name
    + another ObjC typing NAME
  + RESULT:
    + CFFI type as `invoke' result
    + (CFFI-TYPE WRAP)
      + WRAP as `invoke' result wrap function
  + ARG:
    + CFFI type name as argument type
    + a list of (PATTERN EXPAND)

      + see `optima:match' for rule of PATTERN,
      + EXPAND will be evaluated to expand the result
      + if not PATTERN is matched, throw error when `expand-invoke-arg'
      + EXPAND can return two values (EXPAND REWRITE)
        + REWRITE will be used to wrap invoke like:

          (,@REWRITE (invoke ...))
  #+end_example

+ =(define-objc-mask typing* &body binding)= *[Macro]*

  #+name: doc:define-objc-mask
  #+begin_src lisp :exports results
  (documentation (macro-function 'define-objc-mask) t)
  #+end_src

  #+RESULTS: doc:define-objc-mask
  #+begin_example
  Define ObjC mask typing.

  Syntax:

      (define-objc-mask [TYPING|(TYPING &key alias result wrap arg)]
        [DOCSTRING]
        (KEYWORD FLAG-VALUE)
        ...)

  + DOCSTRING: documentation string (optional)
  + KEYWORD, FLAG-VALUE: keyword of flag and responding enum value

  Like `define-objc-typing':
  + ALIAS: by default is :unsigned-long
  + RESULT: by default is parsed with DECODE-<TYPING>
  + ARG: additional matching pattern

  Two functions are created:
  + (AS-<TYPING> &rest FLAGS) to encode FLAGS as ObjC mask value
  + (DECODE-<TYPING> MASK) to decode MASK as flag(s)

  See also `define-objc-enum'.
  #+end_example

+ =(define-objc-enum typing* &body binding)= *[Macro]*

  #+name: doc:define-objc-enum
  #+begin_src lisp
  (documentation (macro-function 'define-objc-enum) t)
  #+end_src

  #+RESULTS: doc:define-objc-enum
  #+begin_example
  Define ObjC enum typing.

  Syntax:

      (define-objc-mask [TYPING|(TYPING &key alias result wrap arg)]
        [DOCSTRING]
        (KEYWORD FLAG-VALUE)
        ...)

  + DOCSTRING: documentation string (optional)
  + KEYWORD, FLAG-VALUE: keyword of flag and responding enum value

  Like `define-objc-typing':
  + ALIAS: by default is :unsigned-long
  + RESULT: by default is parsed with DECODE-<TYPING>
  + ARG: additional matching pattern

  Two functions are created:
  + (AS-<TYPING> FLAG) to encode FLAG as ObjC mask value
  + (DECODE-<TYPING> MASK) to decode MASK as flag

  See also `define-objc-mask'.
  #+end_example

+ =(with-fp-traps-masked &body)= *[Macro, SBCL specific]*

  #+name: doc:with-fp-traps-masked
  #+begin_src lisp :exports results
  (documentation (macro-function 'with-fp-traps-masked) t)
  #+end_src

  #+RESULTS: doc:with-fp-traps-masked
  : Only for SBCL: ignore float traps (often trapped when doing CFFI on macOS).
  : For other Lisp implementations, this will take no effects.

+ =(objc-symbol-value symbol type &optional library)= *[Function]*

  #+name: doc:objc-symbol-value
  #+begin_src lisp :exports results
  (documentation #'objc-symbol-value t)
  #+end_src

  #+RESULTS: doc:objc-symbol-value
  : Lookup foreign ObjC SYMBOL value as TYPE.
  :
  : Possible TYPEs:
  : + :object same as :pointer
  : + :class  interned as `objc-class'
  : + :sel    interned as `sel'
  : + otherwise, CFFI foreign types

+ =(alloc class)= *[Function]*

  #+name: doc:alloc
  #+begin_src lisp :exports results
  (documentation #'alloc t)
  #+end_src

  #+RESULTS: doc:alloc
  : Allocate instance of CLASS.
  : Return foreign-pointer to instance of CLASS (not initialized).

+ =(init object)= *[Function]*

  #+name: doc:init
  #+begin_src lisp :exports results
  (documentation #'init t)
  #+end_src

  #+RESULTS: doc:init
  : Init NS-OBJECT.
  : Return foreign-pointer (same to) NS-OBJECT.

+ =(description object)= *[Function]*

  #+name: doc:description
  #+begin_src lisp :exports results
  (documentation #'description t)
  #+end_src

  #+RESULTS: doc:description
  : Return description string of NS-OBJECT.

+ =(release object)= *[Function]*

  #+name: doc:release
  #+begin_src lisp :exports results
  (documentation #'release t)
  #+end_src

  #+RESULTS: doc:release
  : Release NS-OBJECT.

+ =(retain object)= *[Function]*

  #+name: doc:retain
  #+begin_src lisp :exports results
  (documentation #'retain t)
  #+end_src

  #+RESULTS: doc:retain
  : Retain NS-OBJECT count.
  : Return foreign-pointer (same to) NS-OBJECT.

+ =(autorelease object)= *[Function]*

  #+name: doc:autorelease
  #+begin_src lisp :exports results
  (documentation #'autorelease t)
  #+end_src

  #+RESULTS: doc:autorelease
  : Autorelease NS-OBJECT.
  : Return foreign-pointer (same to) NS-OBJECT.

+ =(osx-version)= *[Function]*

  #+name: doc:osx-version
  #+begin_src lisp :exports results
  (documentation #'osx-version t)
  #+end_src

  #+RESULTS: doc:osx-version
  : Return values as MAJOR MINOR PATCH version of current os version.

+ ~(osx-version>= major &optional minor patch)~ *[Function]*

  #+name: doc:osx-version>=
  #+begin_src lisp :exports results
  (documentation #'osx-version>= t)
  #+end_src

  #+RESULTS: doc:osx-version>=
  : Test if `osx-version' >= MAJOR.MINOR.PATCH
  : Return `t' if pass.
  :
  : Parameters:
  : + MAJOR: major version number
  :   or keyword like `:sequoia', `:tahoe', `:golden-gate'
  : + MINOR: minor version number
  : + PATCH: patch version number

+ =(ns-string-to-string ns-string)= *[Function]*

  #+name: doc:ns-string-to-string
  #+begin_src lisp :exports results
  (documentation #'ns-string-to-string t)
  #+end_src

  #+RESULTS: doc:ns-string-to-string
  : Convert NSString object NS-STRING to lisp string.
  : Return string of NS-STRING.

+ =(string-to-ns-string string)= *[Function]*

  #+name: doc:string-to-ns-string
  #+begin_src lisp :exports results
  (documentation #'string-to-ns-string t)
  #+end_src

  #+RESULTS: doc:string-to-ns-string
  : Convert lisp STRING into NSString object.
  : Return foreign-pointer of NSString for STRING.

+ =(pathname-to-ns-url pathname)= *[Function]*

  #+name: doc:pathname-to-ns-url
  #+begin_src lisp :exports results
  (documentation #'pathname-to-ns-url t)
  #+end_src

  #+RESULTS: doc:pathname-to-ns-url
  : Convert PATHNAME into NSURL.
  : Return foreign-pointer of NSPath for PATHNAME.

+ =(ns-array-to-list ns-array)= *[Function]*

  #+name: doc:ns-array-to-list
  #+begin_src lisp :exports results
  (documentation #'ns-array-to-list t)
  #+end_src

  #+RESULTS: doc:ns-array-to-list
  : Convert NS-ARRAY into list.
  : Return a list of foreign-pointer to NSObject.

+ =(ns-mutable-dictionary ...)= *[Macro]*

  #+name: doc:ns-mutable-dictionary
  #+begin_src lisp :exports results
  (documentation (macro-function 'ns-mutable-dictionary) t)
  #+end_src

  #+RESULTS: doc:ns-mutable-dictionary
  #+begin_example
  Make NSMutableDictionary from KEY-VALS.
  Return foreign-pointer of NSMutableDictionary.

  Syntax:

      (ns-mutable-dictionary
        {KEY VAL}*
        ...)

  Parameters:
  KEY-VALS should be like {KEY VAL}... and would be evaluated
  + KEY
    + foreign-pointer to NSObject
    + `nil':  converted into foreign-pointer to NSNull
    + number: converted into foreign-pointer to NSNumber
  + VAL
    + foreign-pointer to NSObject
    + string: (objc-symbol-value VAL :object)
    + list: (TYPE VALUE)

      TYPE:
      + :ns-string => (string-to-ns-string VALUE)
  #+end_example

+ =(ns-number number)= *[Function]*

  #+name: doc:ns-number
  #+begin_src lisp :exports results
  (documentation #'ns-number t)
  #+end_src

  #+RESULTS: doc:ns-number
  : Convert VAL into NSNumber.
  : Return foreign-pointer to NSNumber.

Load =coca/objc/block= to have Block supports setted up:
+ =(define-objc-block block-type lambda-list)= *[Macro]*

  #+name: doc:define-objc-block
  #+begin_src lisp :exports results
  (documentation (macro-function 'define-objc-block) t)
  #+end_src

  #+RESULTS: doc:define-objc-block
  #+begin_example
  Define ObjC Block of type BLOCK-TYPE.

  Syntax:

      (define-objc-block BLOCK-TYPE LAMBDA-LIST)

  + BLOCK-TYPE: symbol of block type name
  + LAMBDA-LIST: CFFI lambda list element as (VAR CFFI-TYPE)

  Dev Note:
  this will define:
  + CFFI callback with name %objc-<BLOCK-TYPE>-block-callback
  + a macro of name with-objc-<BLOCK-TYPE>-block,
    within macro, use (BLOCK-TYPE lambda-list &body body)
    as callback
  #+end_example
