#+title: Coca.ObjC
#+subtitle: Minimal CFFI ObjC bindings
#+author: 凉凉
* Usage
:PROPERTIES:
:header-args:lisp: :package coca.objc :results verbatim
:END:

** Invoke
Invoke ObjC method with macro [[doc:invoke][=invoke=]]:

#+begin_src lisp
  (description (invoke "NSString" "stringWithUTF8String:" :string "Hello World" :object))
#+end_src

#+RESULTS:
: Hello World

Or use the shortcut function:

#+begin_src lisp :results silent
  (cffi:foreign-funcall "NSLog" :pointer (string-to-ns-string "Hello World"))
#+end_src

which should print out like:

#+begin_example
2026-03-10 20:42:23.575 sbcl[21728:11113876] Hello World
#+end_example

Note that ObjC errors are not handled by lisp, which just kills the lisp
image. Be aware to call ObjC methods correctly or check before calling.

There provides some shortcut functions for some commonly used ObjC methods.
It is adviced to use these functions instead of writing [[doc:invoke][=invoke=]]
(the goal is to provide a lispy and simple code).

For example:
+ [[doc:alloc][=alloc=]]
+ [[doc:init][=init=]]
+ [[doc:description][=description=]]
+ [[doc:release][=release=]]
+ [[doc:retain][=retain=]]
+ [[doc:autorelease][=autorelease=]]

** Typing
The macro [[doc:invoke][=invoke=]] is just a thin warpper on =cffi:foreign-funcall=.

*** ObjC typing via alias
For example:

#+begin_src lisp :eval no
  (invoke "NSString" "stringWithUTF8String:" :string "Hello World" :object)
#+end_src

would be expanded into

#+begin_src lisp :eval no
  (foreign-funcall
   "objc_msgSend"
   :pointer (objc-class-ptr #<NSString 1F9E6A100>)
   :pointer (sel-ptr #<sel stringWithUTF8String: 20890E8C0>)
   :string "Hello World"
   :pointer)
#+end_src

with typing alias:

#+begin_src lisp :eval no
  (define-objc-typing :object
    :alias :pointer)
#+end_src

*** Complex ObjC typing transforming rules
For complex transforming rules:

#+begin_src lisp :eval no
  (invoke ns-object "description" :ns-string)
#+end_src

would be expanded into

#+begin_src lisp :eval no
  (ns-string-to-string
   (foreign-funcall
    "objc_msgSend"
    :pointer (mcclim-coca.objc::objc-pointer ns-object)
    :pointer (mcclim-coca.objc::sel-ptr #<sel description 208A1BFE0>)
    :pointer))
#+end_src

with result and input args rules:

#+begin_src lisp :eval no
  (define-objc-typing :ns-string
    :result (:pointer ns-string-to-string)
    :arg    ((str `(:pointer (string-to-ns-string ,str)))))
#+end_src

the =:arg= parameter can be a list of elements =(PATTERN EXPANSION-RULE)=
+ =PATTERN=: the pattern use [[https://github.com/guicho271828/trivia/][=trivia:match=]] to match patterns
+ =EXPANSION-RULE=: an expression evaluated

  the return value(s) can be arg expansion and invoke rewrite
  + arg expansion: should be like a list of =(:CFFI-TYPE EXPR ...)=
  + invoke rewrite: wrap =invoke= like =`(,@rewrite (invoke ...))=

You can overwrite builtin ObjC type transforming rules to provide
your own syntax sugar. For example, you can use:

#+begin_src lisp :eval no
  (invoke obj "selWithNSDictionary:"
          :object (ns-mutable-dictionary
                   ("KEY" val)))
#+end_src

directly to pass in pointer to =NSDictionary= object,
or you can define [[file:typing.lisp::define-objc-typing :ns-dictionary][=:ns-dictionary=]] so you can use the syntax sugar:

#+begin_src lisp :eval no
  (invoke obj "selWithNsdictionary:"
          :ns-dictionary (("KEY1" val)
                          ("KEY2" (("subNSDictionaryKey1" val)))))
#+end_src

*** Built-in ObjC typing
Coca.ObjC provides some built-in ObjC typing:

| ObjC typing    | CFFI equivent                      | ~invoke~ as return value         |
|----------------+------------------------------------+--------------------------------|
| ~:class~         | ~:pointer~                           | [[doc:coerce-to-objc-class][~coerce-to-objc-class~]]         |
| ~:sel~           | ~:pointer~                           | [[doc:coerce-to-selector][~coerce-to-selector~]]           |
| ~:object~        | ~:pointer~                           |                                |
| ~:ns-array~      | ~:pointer~ (not implemented yet)     | [[doc:ns-array-to-list][~ns-array-to-list~]]             |
| ~:ns-string~     | ~:pointer~ ([[doc:string-to-ns-string][~string-to-ns-string~]])   | [[doc:ns-string-to-string][~ns-string-to-string~]]          |
| ~:ns-url~        | ~:pointer~ ([[doc:pathname-to-ns-url][~pathname-to-ns-url~]])    | [[doc:ns-url-to-pathname][~ns-url-to-pathname~]]           |
| ~:ns-uint~       | ~:unsigned-long~                     | ~:unsigned-long~                 |
| ~:ns-int~        | ~:long~                              | ~:long~                          |
| ~:ns-number~     | ~:pointer~ ([[doc:ns-number][~ns-number~]])             | ~:pointer~ ([[doc:ns-number-value][~ns-number-value~]])   |
| ~:ns-dictionary~ | ~:pointer~ ([[doc:ns-mutable-dictionary][~ns-mutable-dictionary~]]) | ~:pointer~ ([[doc:get-ns-dictionary][~get-ns-dictionary~]]) |
| ~:block~         | ~:pointer~ (ObjC's block)            | (not implemented)              |

Can use [[doc:define-objc-typing][=define-objc-typing=]] macro to define a new ObjC typing.

** Block
Some ObjC functions expect blocks as arguments, which can be invoked
like:

#+begin_src lisp :eval no
  (invoke obj "methodWithBlock:" :block (BLOCK-TYPE (LAMBDA-LIST) &body ...))
#+end_src

Use [[doc:define-objc-block][=define-objc-block=]] to define your own =block-type=.

** Image Dump
Since Coca.ObjC is built on ObjC's runtime, every time you terminate
the ObjC runtime, you have to re-initialize it.

Use [[doc:define-objc-global-variable][=define-objc-global-variable=]] to define a global variable access
function like:

#+begin_src lisp :eval no
  (define-objc-global-variable my-ns-string
    (string-to-ns-string "My NSString")
    "Just to demo it")
#+end_src

Use the function =my-ns-string= to access the global variable
=*my-ns-string*= to ensure it would be correctly setted up.

** macOS version and test
Load =coca/objc/osx-version= subsystem to get the ability to get/test
macOS version.

Use [[doc:osx-version][=(osx-version)=]] to get current macintosh major, minor and patch version.
More commonly, use [[doc:osx-version>=][~(osx-version>= major &optional minor patch)~]] to test
system version requirements.

One of the common usage case would be [[doc:define-objc-enum][=define-objc-enum=]] and
[[doc:define-objc-mask][=define-objc-mask=]] where you could use [[doc:osx-version>=][~osx-version>=~]] to enclude
flags depending on macOS version.

** ObjC Runtime Inspect
It is adviced to load =coca/objc/runtime-inspect= subsystem when developping,
which provides some ObjC runtime functionalities.

The [[Runtime Inspect][API]] provides some MOP-like functions to inspect [[doc:objc-class][=objc-class=]]
hierarchy relationship, method results and else.

* API
:PROPERTIES:
:header-args:lisp: :package coca.objc :results verbatim
:END:

+ =(define-objc-library name &body pairs)= *[Macro]*

  #+name: doc:define-objc-library
  #+begin_src lisp :exports results
    (documentation (macro-function 'define-objc-library) t)
  #+end_src

  #+RESULTS: doc:define-objc-library
  #+begin_example
  Define ObjC library of NAME and load it.

  Syntax:

      (define-objc-library NAME
        (:darwin (:framework \"...\")))

  + NAME: a symbol for foreign library
  + PAIRS: like CFFI `define-foreign-library' PAIRS,
    normally this should be (:darwin (:framework ...))
  #+end_example
+ =(invoke CLASS-OR-OBJECT SEL [TYPE ARG]* [RETURN-TYPE]?)= *[Macro]*

  #+name: doc:invoke
  #+begin_src lisp :exports results
    (documentation (macro-function 'invoke) t)
  #+end_src

  #+RESULTS: doc:invoke
  #+begin_example
  Invokes an ObjC method that returns RESULT CFFI type.

  Syntax:

      (invoke CLASS-OR-OBJECT METHOD
              { OBJC-TYPE VAR }*
              [ (RESULT :void) ])

  Parameters:
  + CLASS-OR-OBJECT: things can be converted via `objc-pointer'
  + METHOD: a string naming the method to invoke
  + OBJC-TYPE: extended CFFI type

    Built-in ObjC typing:
    + :object        expecting to be `objc-object'
    + :class         expecting to be `objc-class'
    + :sel           expecting to be `sel'
    + :ns-string     convert between lisp string and NSString
    + :ns-url        convert between lisp string/pathname and NSURL
    + :ns-uint       alias as :unsigned-long
    + :ns-int        alias as :long
    + :ns-number     convert lisp values to NSNumber
                     adviced to use `ns-number-value' to get NSNumber
                     value back as lisp type
    + :ns-array      convert NSArray into a list of foreign-pointer
                     to NSObject
    + :ns-dictionary input syntax

                         ((KEY VAL)
                          ;; key with nested NSDictionary
                          (KEY ((KEY VAL)
                                (KEY VAL))))

                     creates NSMutableDictionary behind the scene

    Built-in ObjC typing in `coca/objc/block' subsystem:
    + :block    expecting (BLOCK-TYPE (lambda-list ...) ,@body)
      see `define-objc-block' for details

    Built-in ObjC typing in `coca/appkit' subsystem:
    + :ns-rect  expecting (X Y W H) inline value passing
    + :ns-point expecting (X Y) inline value passing
    + :ns-size  expecting (W H) inline value passing

    Use `define-objc-typing' to define new ObjC typing.
  + RESULT:

    Built-in ObjC typing:
    + :ns-array return `list' of `foreign-pointer'

    Use `define-objc-typing' to define new ObjC typing.

    If not provided, by default as `:void'

  See also `invoke-super'.
  #+end_example
+ =(invoke-super OBJECT SEL [TYPE ARG]* [RETURN-TYPE]?)= *[Macro]*

  #+name: doc:invoke-super
  #+begin_src lisp :exports results
    (documentation (macro-function 'invoke-super) t)
  #+end_src

  #+RESULTS: doc:invoke-super
  #+begin_example
  Invokes an ObjC method that returns RESULT CFFI type.

  Syntax:

      (invoke-super OBJECT METHOD
                    { OBJC-TYPE VAR }*
                    [ (RESULT :void) ])

  Parameters:
  + OBJECT: `objc-object'
  + METHOD: a string naming the method to invoke
  + OBJC-TYPE: extended CFFI type

    Built-in ObjC typing:
    + :object        expecting to be `objc-object'
    + :class         expecting to be `objc-class'
    + :sel           expecting to be `sel'
    + :ns-string     convert between lisp string and NSString
    + :ns-url        convert between lisp string/pathname and NSURL
    + :ns-uint       alias as :unsigned-long
    + :ns-int        alias as :long
    + :ns-number     convert lisp values to NSNumber
                     adviced to use `ns-number-value' to get NSNumber
                     value back as lisp type
    + :ns-array      convert NSArray into a list of foreign-pointer
                     to NSObject
    + :ns-dictionary input syntax

                         ((KEY VAL)
                          ;; key with nested NSDictionary
                          (KEY ((KEY VAL)
                                (KEY VAL))))

                     creates NSMutableDictionary behind the scene

    Built-in ObjC typing in `coca/objc/block' subsystem:
    + :block    expecting (BLOCK-TYPE (lambda-list ...) ,@body)
      see `define-objc-block' for details

    Built-in ObjC typing in `coca/appkit' subsystem:
    + :ns-rect  expecting (X Y W H) inline value passing
    + :ns-point expecting (X Y) inline value passing
    + :ns-size  expecting (W H) inline value passing

    Use `define-objc-typing' to define new ObjC typing.
  + RESULT:

    Built-in ObjC typing:
    + :ns-array return `list' of `foreign-pointer'

    Use `define-objc-typing' to define new ObjC typing.

    If not provided, by default as `:void'

  See also `invoke'.
  #+end_example
+ =(with-autorelease-pool &body)= *[Macro]*

  #+name: doc:with-autorelease-pool
  #+begin_src lisp :exports results
    (documentation (macro-function 'with-autorelease-pool) t)
  #+end_src

  #+RESULTS: doc:with-autorelease-pool
  : Wrap BODY within ObjC autorelease pool block.

+ =sel= *[Struct]*

  #+name: doc:sel
  #+begin_src lisp :exports results
    (documentation 'sel 'type)
  #+end_src

  #+RESULTS: doc:sel
  : Wrapper of ObjC SEL.

+ =objc-class= *[Struct]*

  #+name: doc:objc-class
  #+begin_src lisp :exports result
    (documentation 'objc-class 'type)
  #+end_src

  #+RESULTS: doc:objc-class
  : Wrapper of ObjC Class.

+ =(coerce-to-selector sel)= *[Function]*

  #+name: doc:coerce-to-selector
  #+begin_src lisp :exports results
    (documentation #'coerce-to-selector t)
  #+end_src

  #+RESULTS: doc:coerce-to-selector
  : Return cached `sel' for ObjC SEL.

+ =(coerce-to-objc-class class)= *[Function]*

  #+name: doc:coerce-to-objc-class
  #+begin_src lisp :exports results
    (documentation #'coerce-to-objc-class t)
  #+end_src

  #+RESULTS: doc:coerce-to-objc-class
  : Return cached `objc-class' for ObjC Class.

+ =(define-objc-class class superclass &rest protocols)= *[Macro]*

  #+name: doc:define-objc-class
  #+begin_src lisp :exports results
    (documentation (macro-function 'define-objc-class) t)
  #+end_src

  #+RESULTS: doc:define-objc-class
  #+begin_example
  Define ObjC Class if needed.

  This is equal to calling ObjC Code:

  @interface CLASS : SUPERCLASS < PROTOCOLS... >
  @end

  + CLASS:
    string of ObjC Class
  + SUPERCLASS:
    string of superclass of ObjC Class
  + PROTOCOLS:
    strings of ObjC Protocols
  #+end_example
+ =(define-objc-method (class sel &key encoding callback) return-type lambda-list &body)= *[Macro]*

  #+name: doc:define-objc-method
  #+begin_src lisp :exports results
    (documentation (macro-function 'define-objc-method) t)
  #+end_src

  #+RESULTS: doc:define-objc-method
  #+begin_example
  Define ObjC instance method.

  Syntax:

      (define-objc-method (CLASS SEL &key ENCODING CALLBACK)
           RETURN-TYPE
           LAMBDA-LIST
        &body
        SELF...)

  + CLASS:
    literal string of ObjC class name
  + SEL:
    literal string of ObjC SEL name
  + ENCODING:
    method encoding type string
    if not given, will use class_replaceMethod with types as NULL pointer;
    if given, should be like a string starting with @:
  + CALLBACK
    custom CFFI callback symbol name
  + RETURN-TYPE:
    cffi return type with ObjC type enhanced
    + `:object'  same as :pointer
    + `:class'   return value will be wrapped as `objc-class-ptr'
    + `:sel'     return value will be wrapped as `sel-ptr'
    + otherwise see CFFI foreign types
  + LAMBDA-LIST:
    same as `cffi:defcallback', or defined in `define-objc-typing'
  + BODY
    method body,
    within the BODY, self is bound to foreign-pointer of ObjC object
  #+end_example
+ =(define-objc-global-variable reader initial-form &optional documentation)= *[Macro]*

  #+name: doc:define-objc-global-variable
  #+begin_src lisp :exports results
    (documentation (macro-function 'define-objc-global-variable) t)
  #+end_src

  #+RESULTS: doc:define-objc-global-variable
  #+begin_example
  Define ObjC global variable accessor function of NAME.
  The global variable is initialized with INITIALIZE-FORM.

  Syntax:

      (define-objc-global-variable NAME
          INITIALIZE-FORM
        [DOCUMENTATION])

  + NAME: symbol of global reader function name
  + INITIALIZE-FORM: initialization form
  + DOCUMENTATION: optional documentation string for NAME function

  Dev Note:
  + there would also be a global variable with name like `*NAME*'
    it should not be used directly since it should be cleared
    when ObjC runtime initialized and might not properly initialized;
  + this macro acts like `defvar', so if the global variable
    is defined already (and non-nil), it's INITIALIZE-FORM should
    only run once.
  #+end_example
+ =*on-objc-initialization*= *[Variable]*

  #+name: doc:*on-objc-initialization*
  #+begin_src lisp :exports results
    (documentation '*on-objc-initialization* 'variable)
  #+end_src

  #+RESULTS: doc:*on-objc-initialization*
  : A list of ObjC initialize callbacks.
  :
  : The element should be callback function symbol
  : or function to call after `ensure-objc-initialized'.
  :
  : The function will be called with no argument.

+ =(ensure-objc-initialized)=  *[Function]*

  #+name: doc:ensure-objc-initialized
  #+begin_src lisp :exports results
    (documentation #'ensure-objc-initialized t)
  #+end_src

  #+RESULTS: doc:ensure-objc-initialized
  #+begin_example
  Restore ObjC environment after restore image.

  Dev Note:
  1. the ObjC libraries will be reloaded first

     Example: add custom ObjC library

     (define-foreign-library OBJC-LIB
       (:darwin (:framework \"ObjCLibrary\"))
     (pushnew 'OBJC-LIB *objc-libraries*)

  2. the SEL and Class pointer will be rebinded,
     and for thoese dynamic created ObjC class,
     they will be registed at this stage

     it is strongly not recommanded to directly
     store foreign-pointer of `sel' or `objc-class'

  3. the global ObjC variables defined by
     `define-objc-global-variable' will be re-initialized
     using their INITIALIZE-FORM

  4. call hooks in `*on-objc-initialization*'
  #+end_example
+ =(define-objc-typing name &key alias result arg)= *[Macro]*

  #+name: doc:define-objc-typing
  #+begin_src lisp :exports results
    (documentation (macro-function 'define-objc-typing) t)
  #+end_src

  #+RESULTS: doc:define-objc-typing
  #+begin_example
  Define ObjC typing of NAME.

  Syntax:

      (define-objc-typing NAME
        :alias  ALIAS
        :result RESULT
        :arg    ARG)

  + NAME:  (recommanded to be) a keyword for ObjC typing name
  + ALIAS:
    + CFFI typing name
    + another ObjC typing NAME
  + RESULT:
    + CFFI type as `invoke' result
    + (CFFI-TYPE WRAP)
      + WRAP as `invoke' result wrap function
  + ARG:
    + CFFI type name as argument type
    + a list of (PATTERN EXPAND)

      + see `optima:match' for rule of PATTERN,
      + EXPAND will be evaluated to expand the result
      + if not PATTERN is matched, throw error when `expand-invoke-arg'
      + EXPAND can return two values (EXPAND REWRITE)
        + REWRITE will be used to wrap invoke like:

          (,@REWRITE (invoke ...))
  #+end_example
+ =(define-objc-mask typing* &body binding)= *[Macro]*

  #+name: doc:define-objc-mask
  #+begin_src lisp :exports results
    (documentation (macro-function 'define-objc-mask) t)
  #+end_src

  #+RESULTS: doc:define-objc-mask
  #+begin_example
  Define ObjC mask typing.

  Syntax:

      (define-objc-mask [TYPING|(TYPING &key alias result wrap arg)]
        [DOCSTRING]
        (KEYWORD FLAG-VALUE &optional CONDITION)
        ...)

  + DOCSTRING: documentation string (optional)
  + KEYWORD, FLAG-VALUE: keyword of flag and responding enum value
  + CONDITION: conditionally enable or disable KEYWORD
    + an expression whose result is non-nil for enable

    for example:

        (:foo 1 (osx-version>= 26))

    this is tested when macro expand

  Like `define-objc-typing':
  + ALIAS: by default is :unsigned-long
  + RESULT: by default is parsed with DECODE-<TYPING>
  + ARG: additional matching pattern

  Two functions are created:
  + (AS-<TYPING> &rest FLAGS) to encode FLAGS as ObjC mask value
  + (DECODE-<TYPING> MASK) to decode MASK as flag(s)

  See also `define-objc-enum'.
  #+end_example
+ =(define-objc-enum typing* &body binding)= *[Macro]*

  #+name: doc:define-objc-enum
  #+begin_src lisp
    (documentation (macro-function 'define-objc-enum) t)
  #+end_src

  #+RESULTS: doc:define-objc-enum
  #+begin_example
  Define ObjC enum typing.

  Syntax:

      (define-objc-enum [TYPING|(TYPING &key alias type result wrap arg)]
        [DOCSTRING]
        (KEYWORD FLAG-VALUE &optional CONDITION)
        ...)

  + DOCSTRING: documentation string (optional)
  + KEYWORD, FLAG-VALUE: keyword of flag and responding enum value
  + CONDITION: conditionally enable or disable KEYWORD
    + an expression whose result is non-nil for enable

    for example:

        (:foo 1 (osx-version>= 26))

    this is tested when macro expand

  Like `define-objc-typing':
  + ALIAS: by default is `:unsigned-long'
  + TYPE:  by default is `integer'
  + RESULT: by default is parsed with DECODE-<TYPING>
  + ARG: additional matching pattern

  Two functions are created:
  + (AS-<TYPING> FLAG) to encode FLAG as ObjC mask value
  + (DECODE-<TYPING> MASK) to decode MASK as flag

  See also `define-objc-mask'.
  #+end_example

+ =(with-fp-traps-masked &body)= *[Macro, SBCL specific]*

  #+name: doc:with-fp-traps-masked
  #+begin_src lisp :exports results
    (documentation (macro-function 'with-fp-traps-masked) t)
  #+end_src

  #+RESULTS: doc:with-fp-traps-masked
  : Only for SBCL: ignore float traps (often trapped when doing CFFI on macOS).
  : For other Lisp implementations, this will take no effects.

+ =(objc-symbol-value symbol type &optional library)= *[Function]*

  #+name: doc:objc-symbol-value
  #+begin_src lisp :exports results
    (documentation #'objc-symbol-value t)
  #+end_src

  #+RESULTS: doc:objc-symbol-value
  : Lookup foreign ObjC SYMBOL value as TYPE.
  :
  : Possible TYPEs:
  : + :object same as :pointer
  : + :class  interned as `objc-class'
  : + :sel    interned as `sel'
  : + otherwise, CFFI foreign types

+ =(alloc class)= *[Function]*

  #+name: doc:alloc
  #+begin_src lisp :exports results
    (documentation #'alloc t)
  #+end_src

  #+RESULTS: doc:alloc
  : Allocate instance of CLASS.
  : Return foreign-pointer to instance of CLASS (not initialized).

+ =(init object)= *[Function]*

  #+name: doc:init
  #+begin_src lisp :exports results
    (documentation #'init t)
  #+end_src

  #+RESULTS: doc:init
  : Init NS-OBJECT.
  : Return foreign-pointer (same to) NS-OBJECT.

+ =(description object)= *[Function]*

  #+name: doc:description
  #+begin_src lisp :exports results
    (documentation #'description t)
  #+end_src

  #+RESULTS: doc:description
  : Return description string of NS-OBJECT.

+ =(release object)= *[Function]*

  #+name: doc:release
  #+begin_src lisp :exports results
    (documentation #'release t)
  #+end_src

  #+RESULTS: doc:release
  : Release NS-OBJECT.

+ =(retain object)= *[Function]*

  #+name: doc:retain
  #+begin_src lisp :exports results
    (documentation #'retain t)
  #+end_src

  #+RESULTS: doc:retain
  : Retain NS-OBJECT count.
  : Return foreign-pointer (same to) NS-OBJECT.

+ =(autorelease object)= *[Function]*

  #+name: doc:autorelease
  #+begin_src lisp :exports results
    (documentation #'autorelease t)
  #+end_src

  #+RESULTS: doc:autorelease
  : Autorelease NS-OBJECT.
  : Return foreign-pointer (same to) NS-OBJECT.

+ =(ns-string-to-string ns-string)= *[Function]*

  #+name: doc:ns-string-to-string
  #+begin_src lisp :exports results
    (documentation #'ns-string-to-string t)
  #+end_src

  #+RESULTS: doc:ns-string-to-string
  : Convert NSString object NS-STRING to lisp string.
  : Return string of NS-STRING.

+ =(string-to-ns-string string)= *[Function]*

  #+name: doc:string-to-ns-string
  #+begin_src lisp :exports results
    (documentation #'string-to-ns-string t)
  #+end_src

  #+RESULTS: doc:string-to-ns-string
  : Convert lisp STRING into NSString object.
  : Return foreign-pointer of NSString for STRING.

+ =(pathname-to-ns-url pathname)= *[Function]*

  #+name: doc:pathname-to-ns-url
  #+begin_src lisp :exports results
    (documentation #'pathname-to-ns-url t)
  #+end_src

  #+RESULTS: doc:pathname-to-ns-url
  : Convert PATHNAME into NSURL.
  : Return foreign-pointer of NSPath for PATHNAME.

+ =(ns-url-to-pathname ns-url)= *[Function]*

  #+name: doc:ns-url-to-pathname
  #+begin_src lisp :exports results
    (documentation #'ns-url-to-pathname t)
  #+end_src

  #+RESULTS: doc:ns-url-to-pathname
  : Convert NS-URL to pathname.
  : Return a `pathname' instance.

+ =(ns-array-to-list ns-array)= *[Function]*

  #+name: doc:ns-array-to-list
  #+begin_src lisp :exports results
    (documentation #'ns-array-to-list t)
  #+end_src

  #+RESULTS: doc:ns-array-to-list
  : Convert NS-ARRAY into list.
  : Return a list of foreign-pointer to NSObject.

+ =(ns-mutable-dictionary ...)= *[Macro]*

  #+name: doc:ns-mutable-dictionary
  #+begin_src lisp :exports results
    (documentation (macro-function 'ns-mutable-dictionary) t)
  #+end_src

  #+RESULTS: doc:ns-mutable-dictionary
  #+begin_example
  Make NSMutableDictionary from KEY-VALS.
  Return foreign-pointer of NSMutableDictionary.

  Syntax:

      (ns-mutable-dictionary
        {KEY VAL}*
        ...)

  Parameters:
  KEY-VALS should be like {KEY VAL}... and would be evaluated
  + KEY
    + foreign-pointer to NSObject
    + `nil':  converted into foreign-pointer to NSNull
    + number: converted into foreign-pointer to NSNumber
  + VAL
    + foreign-pointer to NSObject
    + string: (objc-symbol-value VAL :object)
    + list: (TYPE VALUE)

      TYPE:
      + :ns-string => (string-to-ns-string VALUE)
  #+end_example
+ =(get-ns-dictionary dictionary key)= *[Function]*

  #+name: doc:get-ns-dictionary
  #+begin_src lisp :exports results
    (documentation #'get-ns-dictionary t)
  #+end_src

  #+RESULTS: doc:get-ns-dictionary
  #+begin_example
  Get/Set object in DICTIONARY of KEY.
  Return result specificed by RESULT.

  Parameters:
  + DICTIONARY: foreign-pointer to NSDictionary
  + KEY:
    + foreign-pointer: foreign-pointer to NSObject
    + string: use (objc-symbol-value KEY :pointer) as key
    + list of (TYPE LISP-VALUE):
      + (:ns-string STRING)
        use NSString as key
  + RESULT:
    + `:object', `:pointer': return the foreign-pointer
    + `:ns-string': convert NSString as string
    + `:bool', `:char', `:float', `:double', `:int', `:string'
      treat value as NSNumber and decoded with `ns-number-value'

  Dev Note:
  + when (setf (get-ns-dictionary dictionary key) value)
    the DICTIONARY should be foreign-pointer to NSMutableDictionary,
    sadly, this won't be checked when setting the value
  + when setf, the VALUE might be:
    + foreign-pointer
    + nil: treat as [NSNull null]
    + string: treat as NSString
    + number: converted using `ns-number'
  #+end_example
+ =(ns-number number)= *[Function]*

  #+name: doc:ns-number
  #+begin_src lisp :exports results
    (documentation #'ns-number t)
  #+end_src

  #+RESULTS: doc:ns-number
  #+begin_example
  Convert VAL into NSNumber.
  Return foreign-pointer to NSNumber.

  Parameter:
  + VAL
    might be:
    + boolean
    + character
    + integer
    + float
  #+end_example
+ =(ns-number-value ns-number type)= *[Function]*

  #+name: doc:ns-number-value
  #+begin_src lisp :exports results
    (documentation #'ns-number-value t)
  #+end_src

  #+RESULTS: doc:ns-number-value
  #+begin_example
  Convert pointer to NS-NUMBER into TYPE lisp value.
  Return value of TYPE.

  Parameters:
  + NS-NUMBER:
    foreign-pointer to NSNumber instance
  + TYPE:
    + `:bool'
    + `:char'
    + `:double'
    + `:float'
    + `:int'
    + `:string'
  #+end_example

** Block
Load =coca/objc/block= to have Block supports setted up:
+ =(define-objc-block block-type lambda-list)= *[Macro]*

  #+name: doc:define-objc-block
  #+begin_src lisp :exports results
    (documentation (macro-function 'define-objc-block) t)
  #+end_src

  #+RESULTS: doc:define-objc-block
  #+begin_example
  Define ObjC Block of type BLOCK-TYPE.

  Syntax:

      (define-objc-block BLOCK-TYPE LAMBDA-LIST)

  + BLOCK-TYPE: symbol of block type name
  + LAMBDA-LIST: CFFI lambda list element as (VAR CFFI-TYPE)

  Dev Note:
  this will define:
  + CFFI callback with name %objc-<BLOCK-TYPE>-block-callback
  + a macro of name with-objc-<BLOCK-TYPE>-block,
    within macro, use (BLOCK-TYPE lambda-list &body body)
    as callback
  #+end_example

** OSX-Version
Load =coca/objc/osx-version= to have macOS version support:
+ =(osx-version)= *[Function]*

  #+name: doc:osx-version
  #+begin_src lisp :exports results
    (documentation #'osx-version t)
  #+end_src

  #+RESULTS: doc:osx-version
  : Return values as MAJOR MINOR PATCH version of current os version.

+ ~(osx-version>= major &optional minor patch)~ *[Function]*

  #+name: doc:osx-version>=
  #+begin_src lisp :exports results
    (documentation #'osx-version>= t)
  #+end_src

  #+RESULTS: doc:osx-version>=
  : Test if `osx-version' >= MAJOR.MINOR.PATCH
  : Return `t' if pass.
  :
  : Parameters:
  : + MAJOR: major version number
  :   or keyword like `:sequoia', `:tahoe', `:golden-gate'
  : + MINOR: minor version number
  : + PATCH: patch version number

** Runtime Inspect
Load =coca/objc/runtime-inspect= to have ObjC runtime environment
inspection abilities. Note that this package should only for
development usage (not recommanded to use in production environemnt).

+ =(objc-class-list)= *[Function]*

  #+name: doc:objc-class-list
  #+begin_src lisp :exports results
    (documentation #'objc-class-list t)
  #+end_src

  #+RESULTS: doc:objc-class-list
  : Return a list of all the ObjC classes.

+ =(objc-class-superclass objc-class)= *[Function]*

  #+name: doc:objc-class-superclass
  #+begin_src lisp :exports results
    (documentation #'objc-class-superclass t)
  #+end_src

  #+RESULTS: doc:objc-class-superclass
  : Return the superclass of OBJC-CLASS.
  :
  : If the OBJC-CLASS is the root class, its superclass is `t',
  : otherwise, return `objc-class'.

+ =(objc-class-subclassp class superclass)= *[Function]*

  #+name: doc:objc-class-subclassp
  #+begin_src lisp :exports results
    (documentation #'objc-class-subclassp t)
  #+end_src

  #+RESULTS: doc:objc-class-subclassp
  : Test if CLASS is subclass of SUPERCLASS.

+ =(objc-class-subclasses objc-class)= *[Function]*

  #+name: doc:objc-class-subclasses
  #+begin_src lisp :exports results
    (documentation #'objc-class-subclasses t)
  #+end_src

  #+RESULTS: doc:objc-class-subclasses
  : Return a list of subclasses of OBJC-CLASS.

+ =(decode-objc-type-encoding encoding)= *[Function]*

  #+name: doc:decode-objc-type-encoding
  #+begin_src lisp :exports results
    (documentation #'decode-objc-type-encoding t)
  #+end_src

  #+RESULTS: doc:decode-objc-type-encoding
  #+begin_example
  Parse ObjC type encoding string ENCODING.
  Return values are list ObjC encoding, and ENCODING string.

  Dev Note:

    <type>    := :char | :int | :short | ... ;; see below
    <array>   := (:array len <type>)
    <struct>  := (:struct name (<type>...))
    <union>   := (:union name (<type>...))

  ObjC type encoding: (
    Code             ObjC encoding       Meaning
    c                :char               A char
    i                :int                An int
    s                :short              A short
    l                :long               A long
    q                :long-long          A long long
    C                :unsigned-char      An unsigned char
    I                :unsigned-int       An unsigned int
    S                :unsigned-short     An unsigned short
    L                :unsigned-long      An unsigned long
    Q                :unsigned-long-long An unsigned long long
    f                :float              A float
    d                :double             A double
    B                :bool               A C++ bool or a C99 _Bool
    v                :void               A void
    ,*                :string             A character string (char *)
    @                :object             An object (whether statically typed or typed id)
    #                :class              A class object (Class)
    :                :sel                A method selector (SEL)
    [array type]     (:array len enc)    An array
    {name=type . ..} (:struct NAME)      A structure
    (name=type . ..) (:union  NAME)      A union
    bnum             (:bits NUM)         A bit field of num bits
    ^type            :pointer            A pointer to type
    ?                :unknown            An unknown type

  ObjC method encoding:
    r                         const
    n                         in
    N                         inout
    o                         out
    O                         bycopy
    R                         byref
    V                         oneway

  see also:
  https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/ObjCRuntimeGuide/Articles/ocrtTypeEncodings.html
  #+end_example
+ =(encode-objc-type-encoding objc-encoding-list)= *[Function]*

  #+name: doc:encode-objc-type-encoding
  #+begin_src lisp :exports results
    (documentation #'encode-objc-type-encoding t)
  #+end_src

  #+RESULTS: doc:encode-objc-type-encoding
  : Encode OBJC-ENCODING-LIST as ObjC type encoding string.
  : Return ObjC type encoding string.
  :
  : Example:
  :
  :     (encode-objc-type-encoding '(:void :object :sel)) ;; => \"v@:\"

+ =(objc-class-instance-method-encoding objc-class-or-object sel &optional errorp objc-class-p)= *[Function]*

  #+name: doc:objc-class-instance-method-encoding
  #+begin_src lisp :exports results
    (documentation #'objc-class-instance-method-encoding t)
  #+end_src

  #+RESULTS: doc:objc-class-instance-method-encoding
  #+begin_example
  Get class instance method encoding of OBJC-CLASS and SEL.
  Return values are argument encoding list, return type and encoding string.
  If not found and not ERRORP, return `nil'.

  Parameters:
  + OBJC-CLASS-OR-OBJECT:
    + foreign-pointer to object
    + otherwise, would be `coerce-to-objc-class'
  + SEL: would be `coerce-to-selector' first
  + ERRORP: if or not error when class method is not found
  + OBJC-CLASS-P:
    if non-nil, assume OBJC-CLASS-OR-OBJECT is pointer to ObjC class
  #+end_example

+ =(objc-class-class-method-encoding objc-class sel &optional errorp)= *[Function]*

  #+name: doc:objc-class-class-method-encoding
  #+begin_src lisp :exports results
    (documentation #'objc-class-class-method-encoding t)
  #+end_src

  #+RESULTS: doc:objc-class-class-method-encoding
  : Get class method encoding of OBJC-CLASS and SEL.
  : Return values are argument encoding list, return type and encoding string.
  : If not found and not ERRORP, return `nil'.
  :
  : Parameters:
  : + OBJC-CLASS: would be `coerce-to-objc-class' first
  : + SEL: would be `coerce-to-selector' first
  : + ERRORP: if or not error when class method is not found
