:PROPERTIES:
:header-args:lisp: :package coca :wrap example :exports results
:END:
#+title: Coca
#+subtitle: Cocoa in Common Lisp
#+author: 凉凉
* About
#+begin_src lisp :exports results
(asdf:system-description (asdf:find-system :coca))
#+end_src

#+RESULTS:
#+begin_example
Cocoa in Common Lisp
#+end_example

*NOTE*: currently, only tested on SBCL (2.5.10) on macOS.
cannot ensure and won't provide support for other implementation
or other platform (right now). But contributions are welcomed.

* Documentations
Coca is (or *SHOULD BE*) self-documented.
Load the system and use =sly-describe-symbol= or SLIME functions
to read the documentation of each symbol.

** Examples
A few examples could be found under [[file:examples][=examples=]] directory.

* Subsystems
** Coca/ObjC
Loads =coca/objc= and use package =:coca.objc= (see [[file:objc/readme.org][objc/readme]] for details).

** Coca/Frameworks
Load =coca/frameworks= will only loads
=coca/frameworks/foundation= and =coca/frameworks/appkit=.

*** Coca/Frameworks/Foundation
#+begin_src lisp :exports results
(str:concat
 (asdf:system-description      (asdf:find-system :coca/frameworks/foundation))
 (string #\Newline)
 (string #\Newline)
 (asdf:system-long-description (asdf:find-system :coca/frameworks/foundation)))
#+end_src

#+RESULTS:
#+begin_example
ObjC bindings of Foundation Framework

Access essential data types, collections, and operating-system services to
define the base layer of functionality for your app.

The Foundation framework provides a base layer of functionality for apps and
frameworks, including data storage and persistence, text processing, date and
time calculations, sorting and filtering, and networking. The classes, protocols,
and data types defined by Foundation are used throughout the macOS, iOS,
watchOS, and tvOS SDKs.

see https://developer.apple.com/documentation/Foundation?language=objc
#+end_example

*** Coca/Frameworks/Appkit
#+begin_src lisp :exports results
(str:concat
 (asdf:system-description      (asdf:find-system :coca/frameworks/appkit))
 (string #\Newline)
 (string #\Newline)
 (asdf:system-long-description (asdf:find-system :coca/frameworks/appkit)))
#+end_src

#+RESULTS:
#+begin_example
ObjC bindings of AppKit Framework

Construct and manage a graphical, event-driven user interface for your macOS app.

AppKit contains the objects you need to build the user interface for a macOS app.
In addition to drawing windows, buttons, panels, and text fields, it handles all the
event management and interaction between your app, people, and macOS.

see https://developer.apple.com/documentation/AppKit?language=objc
#+end_example

*** Coca/Frameworks/Webkit
#+begin_src lisp :exports results
(str:concat
 (asdf:system-description      (asdf:find-system :coca/frameworks/webkit))
 (string #\Newline)
 (string #\Newline)
 (asdf:system-long-description (asdf:find-system :coca/frameworks/webkit)))
#+end_src

#+RESULTS:
#+begin_example
ObjC bindings of Webkit Framework

Integrate web content seamlessly into your app,
and customize content interactions to meet your app's needs.

Use the WebKit framework to integrate richly styled web content into your
app's native content. WebKit offers a full browsing experience for your content,
offering a platform-native view and supporting classes to:

+ Display rich web content using HTML, CSS, and JavaScript
+ Handle the incremental loading of page content
+ Display multiple MIME types and compound frame elements
+ Navigate between pages of content
+ Manage a forward-back list of recently visited pages

For more information about WebKit, go to https://webkit.org.

see https://developer.apple.com/documentation/WebKit?language=objc
#+end_example

* Dev Note
** License
=Coca= is distributed under the LLGPL (Lisp Lesser General Public
License). You are free to use =Coca= as a library within your commercial
Cocoa applications. However, I kindly ask that any improvements or
modifications to Coca itself remain open-sourced, so that the entire
community can benefit and Coca can continue to evolve through your
contributions.

** How to Contribute
*** ObjC frameworks
**** No wrapping, just use =Coca/ObjC=
If you just want to do some rapid prototyping or you need something
that are not provided with =Coca= currently, you can use functions
provided in =Coca/ObjC= to call ObjC methods directly:

For example:
+ =[object SEL ...]= could be written as =(invoke object SEL ...)=

Note that it's also recommanded to load =Coca/Frameworks= system
(or at least =Coca/Frameworks/Foundation=) since it wrapps a lot
of ObjC method in the lispy style.

**** Trivial wrapping with =devtools/parse-apple-docs.js=
I wrote a helper script in =devtools/parse-apple-docs.js=, which
could be used to extract definitions from Apple's documentation
website. It maynot always generate correct code so use it with
caution.

**** Lispy wrapper codes
*Style Guide*:
+ =define-objc-const=:
  the const should be named like =+const-name+=

  Example:
  + =+ns-foundation-version-number+=

*Values converting*:
+ =as-xxx=:
  convert lisp values into ObjC form

  Example:
  + =as-boolean=: convert values as ObjC =:bool=
  + =as-ns-font=:

+ =decode-xxx=:
  defined by =define-objc-enum= to convert ObjC mask/enum as lisp flags

*Methods*:
+ use lisp methods rather than ObjC methods

  Example:
  + instead of writing

    #+begin_src lisp :eval no
    (define-objc-method ("MyWindow" "init") :object ()
      (invoke (super) "init")
      (invoke self "..."))
    #+end_src

    use lisp method to replace the initialize logic like:

    #+begin_src lisp :eval no
    (defmethod init ((window 'my-window))
      (call-next-method)
      (invoke window "..."))
    #+end_src
  + instead of writing

    #+begin_src lisp :eval no
    (define-objc-method ("ClassA" "method") :void ()
      (do-something))

    (define-objc-method ("SubclassOfClassA" "method") :void ()
      (invoke (super) "method")
      (do-something))
    #+end_src

    regist ObjC method in "root" class and use CLOS method
    to process different classes

    #+begin_src lisp :eval no
    (defgeneric method (object))

    (define-objc-method ("ClassA" "method") :void
      (method self))

    (defmethod ((object subclass-of-class-a))
      ...)
    #+end_src

*Generic functions*:
+ =init=: implement =init= to set the logic of creating an ObjC object

  Example:

  + =(init (alloc 'ns-window) :frame (make-ns-rect :w 200 :h 200))=

*** Optimization of =Coca/ObjC=
I cannot say that current =Coca/ObjC= is perfectly working.
The code and the performance should be more robust.

* Reference
+ [[https://developer.apple.com/documentation][Apple's Documentation]]
+ [[https://github.com/gammasoft71/Examples_Cocoa/][Cocoa examples (github:gammasoft71/Examples_Cocoa)]]

  some of the examples are learnt from this repo
+ [[https://github.com/EimaKve/Silicon][Silicon.h (github:EimaKve/Silicon)]]

  some of the examples are learnt from this repo

Below is the developping notes on my blog (mostly Chinese):
+ [[https://li-yiyang.github.io/lisp/objc/objc-0/][ObjC (00): ObjC Runtime Inspector]]
+ [[https://li-yiyang.github.io/lisp/objc-ns-exception/][ObjC (1.5) NSException (EN)]]
+ [[https://li-yiyang.github.io/lisp/objc-libffi/][ObjC (1.75) libffi, cffi, cffi-grovel, and C]]
